### ISSUE TITLE
AutoValueFactory not generated when no AutoValue has a static typeAdapter method

### ISSUE THREAD

**Issue by h0ngyue** [rharter/auto-value-gson#107]
If my new-born project ,i move a lot of reusable module from my old project to the new one which include some AutoGsonAdapterFactory ,and turn out i found that when , if there is no @AutoValue-Class  or no one of them has the "TypeAdapter<SomeData> typeAdapter(Gson gson)" method in a module, the AutoValueGson_SomeModuleAutoGsonAdapterFactory won't be generated(I put the  factory there for future use only ,and not come up with some adapter need yet). Although there is indeed no need of the AutoGsonAdapterFactory, but the compile failure(Facotry class not found) make me confused and take some time to find out the reason for the failure.  
so ,hopefully , it's would be nice if the  README can friendly add a Tip or a detailed compile error message to avoid this.
Thanks

**Comment by rharter** [comment]
The first sentence of the usage section states that you need to add the static method for auto-value-gson to do anything. I'd be open to a warning message for this. 

"Simply include auto-value-gson in your project and add a public static method to your @AutoValue annotated class returning a TypeAdapter."
