### ISSUE TITLE
Gson deserialize NumberFormatException : empty string

### ISSUE THREAD

**Issue by UsherBaby** [rharter/auto-value-gson#112]
Unable to deserialize empty string field to int or boolean type .
Can you catch these exceptions and give a default value to them

**Comment by autonomousapps** [comment]
I believe this has already been dealt with, but there hasn't been an official release since that PR was merged.

**Comment by UsherBaby** [comment]
@autonomousapps Thanks for reminding

**Comment by autonomousapps** [comment]
v0.4.6 was just released. Should have the feature you're looking for.

**Comment by UsherBaby** [comment]
@autonomousapps Version 0.4.6 still has the problem .

**Comment by autonomousapps** [comment]
Oh, I think I misunderstood you. Sorry! The feature I was thinking of converts `null` values to defaults, not empty strings.

**Comment by UsherBaby** [comment]
@autonomousapps Maybe this responsibility belongs to gson . I register TypeAdapter to solve the problem . Thanks ! Please close this issue

**Comment by rharter** [comment]
@UsherBaby Agreed, treating empty strings as nulls, or even strings as ints or booleans isn't really the job of this library (or even Gson, that's just broken JSON), so should be handled elsewhere.
