### ISSUE TITLE
Gson does not correctly serialize with polymorphism  

### ISSUE THREAD

**Issue by inktomi** [rharter/auto-value-gson#113]
If you have a base class that has some properties, and then another class which extends it - you do not get any of the properties from either class in the resulting JSON output. 

You can see this behavior demonstrated here: https://github.com/inktomi/auto-value-gson-bug

Run the `ExtensionTest` class. You can see that the `Extension` class has a `type` in it, defined as a `BaseType`. We set that to an autovalue `CarType` and then write out the JSON. Is it expected that in the resulting JSON the `type` is `"type":{}`? 

I would expect that Gson should be configured to know the possible types of `BaseType` and choose the correct one using the `TypeToken` available at serialization/deserialization time.

**Comment by JakeWharton** [comment]
I'm not sure this is the problem of this extension as the exact same behavior would happen if you used Gson directly. You need to create a polymorphic type adapter for `BaseType` which either defers lookup of the actual type until serialization time or registers a list of available type adapters to delegate to based on the runtime type.

**Comment by inktomi** [comment]
I agree. I'm fine with closing this out as "not a bug", but as that code is somewhat formulaic to write it might be nice to generate it if possible, since the actual `@AutoValue` types all have their own type adapters available for use.

**Comment by JakeWharton** [comment]
Yeah that makes sense. A problem might be though that this code could be in a library and then there are other subclasses of `BaseType` in other modules that consume the library. In order for what you propose to work there'd have to be a guarantee that it's a sealed type where no more subclasses would be created.

**Comment by jzillmann** [comment]
Running into an issue which sounds similar to that...
Base class looks like that:
```
public abstract class TrackerEvent {

    private final String _type;

    public TrackerEvent(String type) {
        _type = type;
    }

    public String type() {
        return _type;
    }

}
```

Then the auto-value class:
```
@AutoValue
public abstract class AppInit extends TrackerEvent {

    public AppInit() {
        super("APP_INIT");
    }
...
```

Using a Gson without the generated type adapter will serialize the _type field.
Using a Gson with the generated type adapter will not serialize the _type field.

**Comment by hzsweers** [comment]
Nothing else to be done here, this is more of a gson usage nuance.
