### ISSUE TITLE
Better logging

### ISSUE THREAD

**Issue by mturki** [rharter/auto-value-gson#119]
Improve login on debug time. I'm using auto-value-gson with retrofit, and i forgot to annotate a String as @Nullable in a nested custom type (Our api returns null values for empty strings :-/). All my calls ended systematically in my onFailure(Call<User> call, Throwable t) callback, with a "java.lang.NullPointerException: Null scope" as Throwable. It's of course my fault. But i spent a lot of time understanding and debugging (it's my very first auto value implementation). Is-it possible to have more details on the error or about offending field (or class)?

**Comment by rharter** [comment]
Was the field called `scope`?

**Comment by mturki** [comment]
Sorry, yes, in fact, the field is called ’scope’. I was lost in my logs. I did not associate the log error ’ Null scope’ with an existing json field.
