### ISSUE TITLE
GsonTypeAdapter not generated for default or protected TypeAdapter methods

### ISSUE THREAD

**Issue by jakekdodd** [rharter/auto-value-gson#121]
From the readme:
> To trigger TypeAdapter generation, you need include a **non-private** static factory method

(emph. mine).

I was hoping something like this would work, but it's not currently supported:

```java
@AutoValue abstract class Foo {
    static TypeAdapter<Foo> typeAdapter(Gson gson) {
        return new AutoValue_Foo.GsonTypeAdapter(gson);
     }

    abstract String bar();
}
```

**Comment by rharter** [comment]
Thanks, we just dealt with this over on the Moshi extension.  I appreciate the PR!

**Comment by jakekdodd** [comment]
👍 thanks for merging so quickly!
