### ISSUE TITLE
Null support for objects?

### ISSUE THREAD

**Issue by scottazord** [rharter/auto-value-gson#125]
Hey All,

I'm just wondering if there is any null support for nullable objects.

My response object looks like such:

```
@AutoValue
public abstract class MyObject implements Parcelable {

    /**
     * Name can be null
     */
    @SerializedName("A")
    public abstract String getName();


    public static TypeAdapter<MyObject> typeAdapter(Gson gson) {
        return new AutoValue_MyObject.GsonTypeAdapter(gson);
    }
}
```

When i retrieve a nullable object, i get the following:

java.lang.NullPointerException: Null name

Am i incorrect in assuming this is supported out of the box?

Thanks,
Scott.

**Comment by hzsweers** [comment]
Please paste the full stacktrace. Also check out gson's `.nullSafe()` API on `TypeAdapter`s

**Comment by hzsweers** [comment]
This is a question for autovalue, not auto-value-gson. You can use any `@Nullable` annotation and autovalue will recognize it, please read their docs.

**Comment by autonomousapps** [comment]
If you annotate your abstract method with `@Nullable`, it will be able to deserialize it to `null`
