### ISSUE TITLE
How to eliminate the warning message of warning: The following options were not recognized by any processor: '[autovaluegson.defaultCollectionsToEmpty]'

### ISSUE THREAD

**Issue by TonyTangAndroid** [rharter/auto-value-gson#128]
If I add

```gradle
android {
  defaultConfig {
    javaCompileOptions {
      annotationProcessorOptions {
        arguments = ['autovaluegson.defaultCollectionsToEmpty': 'true']
      }
    }
  }
}
```

into build.gradle script in the module level, when it builds the project, it will always shows certain warnming message even through everything works ok. Feel free to check out this [repo](https://github.com/TonyTangAndroid/AutoValueWarningMessageDemo) to reproduce this warning. 

> warning: The following options were not recognized by any processor: '[autovaluegson.defaultCollectionsToEmpty]'
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by JakeWharton** [comment]
This happens when compiling source sets other than the main one like JVM tests or instrumentation tests. It can safely be ignored.

**Comment by cdeange** [comment]
Would overriding [getSupportedOptions()](https://docs.oracle.com/javase/7/docs/api/javax/annotation/processing/AbstractProcessor.html#getSupportedOptions()) in the processor to return that option key eliminate the warning?

**Comment by hzsweers** [comment]
No, because AV extensions don't have that option

**Comment by AmitBarjatya** [comment]
I am facing a similar issue : `Information:Gradle tasks [installDebug]
Warning:The following options were not recognized by any processor: '[autovaluegson.defaultCollectionsToEmpty]'
Error:Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {--input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/63.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/67.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/27.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/31.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/55.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/59.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/79.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/83.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/12.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/16.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/2.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/6.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/78.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/82.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/76.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/80.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/46.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/50.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/61.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/65.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/74.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/78.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/32.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/36.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/56.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/60.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/45.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/49.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/62.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/66.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/18.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/22.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/15.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/19.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/77.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/81.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/71.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/75.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/49.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/53.jar --input /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/34.jar --output /home/amit/supply_android/app/build/intermediates/transforms/desugar/debug/38.jar --classpath_entry /home/amit/supply_android/app/libs/labelview/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /home/amit/supply_android/app/libs/multipleimageselect/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /home/amit/supply_android/app/libs/android-auto-scroll-view-pager/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/classes/debug --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/0.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/1.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/2.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/3.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/4.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/5.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/6.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/7.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/8.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/9.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/10.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/11.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/12.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/13.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/14.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/15.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/16.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/17.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/18.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/19.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/20.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/21.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/22.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/23.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/24.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/25.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/26.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/27.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/28.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/29.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/30.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/31.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/32.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/33.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/34.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/35.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/36.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/37.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/38.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/39.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/40.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/41.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/42.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/43.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/44.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/45.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/46.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/47.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/48.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/49.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/50.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/51.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/52.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/53.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/54.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/55.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/56.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/57.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/58.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/59.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/60.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/61.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/62.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/63.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/64.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/65.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/66.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/67.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/68.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/69.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/70.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/71.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/72.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/73.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/74.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/75.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/76.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/77.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/78.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/79.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/80.jar --classpath_entry /home/amit/supply_android/app/build/intermediates/transforms/stackFramesFixer/debug/81.jar --classpath_entry /home/amit/.gradle/caches/modules-2/files-2.1/com.github.rharter/auto-value-gson/4af01db/6db7d421f47e1bf14524e01e279843765c61c78b/auto-value-gson-4af01db.jar --classpath_entry /home/amit/.gradle/caches/modules-2/files-2.1/com.jakewharton.auto.value/auto-value-annotations/1.4/cb7c6499213f6ba1d01f18c27ff1dd6a47a9400d/auto-value-annotations-1.4.jar --classpath_entry /home/amit/.gradle/caches/modules-2/files-2.1/com.squareup/javapoet/1.8.0/e858dc62ef484048540d27d36f3ec2177a3fa9b1/javapoet-1.8.0.jar --classpath_entry /home/amit/.gradle/caches/modules-2/files-2.1/com.google.auto.value/auto-value/1.3/4961194f62915eb45e21940537d60ac53912c57d/auto-value-1.3.jar --classpath_entry /home/amit/.gradle/caches/modules-2/files-2.1/com.google.auto.service/auto-service/1.0-rc2/51033a5b8fcf7039159e35b6878f106ccd5fb35f/auto-service-1.0-rc2.jar --classpath_entry /home/amit/.gradle/caches/modules-2/files-2.1/com.google.auto/auto-common/0.6/cf7212b0f8bfef12657b942df8f4f2cf032d3f41/auto-common-0.6.jar --classpath_entry /home/amit/android-studio/gradle/m2repository/com/google/guava/guava/18.0/guava-18.0.jar --bootclasspath_entry /home/amit/Android/Sdk/platforms/android-27/android.jar --bootclasspath_entry /home/amit/Android/Sdk/platforms/android-27/optional/org.apache.http.legacy.jar --bootclasspath_entry /home/amit/android-studio/jre/jre/lib/resources.jar --bootclasspath_entry /home/amit/android-studio/jre/jre/lib/rt.jar --bootclasspath_entry /home/amit/android-studio/jre/jre/lib/jsse.jar --bootclasspath_entry /home/amit/android-studio/jre/jre/lib/jce.jar --bootclasspath_entry /home/amit/android-studio/jre/jre/lib/charsets.jar --min_sdk_version 21 --nodesugar_try_with_resources_if_needed --desugar_try_with_resources_omit_runtime_classes}
Information:BUILD FAILED in 32s
Information:1 error
Information:1 warning
Information:See complete output in console`

Contrary to the OP, where everything still ran, it's not letting me run my project on a device with Android studio 3.0. Any ideas why?

**Comment by hzsweers** [comment]
I've submitted a proposal PR to add this support to AutoValue's extensions API here - https://github.com/google/auto/pull/680

**Comment by hzsweers** [comment]
We're going to remove this option entirely via #197, so closing this out with it. Upstream PR still makes sense, but won't affect this library for now
