### ISSUE TITLE
Generated TypeAdapters using Reflection

### ISSUE THREAD

**Issue by solcott** [rharter/auto-value-gson#13]
The TypeAdapterFactories generated by auto-value-gson are using reflection, which is inefficient on Android.  Since Android apps usually need to register type adapter factories at application start up this causes a significant delay in app start up.

For example for `List<String>` the following is generated in the TypeAdapterFactories constructor:
`stringAdapter = gson.getAdapter(new TypeToken<List<String>(){})`

Inside the default TypeToken constructor is where the reflection happens:
`this.type = getSuperclassTypeParameter(getClass());`

A better way would be to create an instance of `java.lang.reflect.ParameterizedType` and pass it into `gson.getAdapter()`.  Unfortunately the only implementations of  `java.lang.reflect.ParameterizedType` are either in Guava or are in internal packages in Gson.  In Gson you can create one by calling `com.google.gson.internal.$Gson$Types#newParameterizedTypeWithOwner(null, List.class, String.class)`.  Again this is an internal class so probably don't want to rely on it.

The only other solution would be to create an implementation of ParameterizedType and use it.  This would have to be a compile time dependency of the client library or application.

Here is a hacky method I created that would use the `com.google.gson.internal.$Gson$Types#newParameterizedTypeWithOwner(null, List.class, String.class)` solution.  Unfortunately it doesn't handle more complicated scenarios where the  ParameterizedType includes another ParameterizedType like `List<Set<String>>` or `Map<String, Set<String>>`

```
private CodeBlock getParameterizedTypeConstructorStatement(ParameterizedTypeName type, FieldSpec field, ParameterSpec gsonParam) {
    CodeBlock.Builder block = CodeBlock.builder();
    try {
      int typeArgsSize = type.typeArguments.size();
      int argsIndex = 0;
      Object[] args = new Object[5 + (typeArgsSize)];
      args[argsIndex++] = field;
      args[argsIndex++] = type;
      args[argsIndex++] = gsonParam;
      args[argsIndex++] = ClassName.get($Gson$Types.class);
      args[argsIndex++] = type.rawType;
      String[] genericTypesFormatWithClass = new String[typeArgsSize];
      for (int i = 0; i < typeArgsSize; i++) {
        args[argsIndex++] = type.typeArguments.get(i);
        genericTypesFormatWithClass[i] = "$T.class";
      }
      StringBuilder blockString = new StringBuilder("this.$N = (TypeAdapter<$T>) $N.getAdapter(TypeToken.get($T.newParameterizedTypeWithOwner(null,$T.class,");
      Joiner.on(",").appendTo(blockString, genericTypesFormatWithClass);
      blockString.append(")))");
      block.addStatement(blockString.toString(), args);
    }catch (Exception e){
      //Fall back on using reflection
      block.addStatement("this.$N = $N.getAdapter(new TypeToken<$T>(){})", field,gsonParam, type);
    }
```

**Comment by JakeWharton** [comment]
> Since Android apps usually need to register type adapter factories at application start up this causes a significant delay in app start up.

You do not need to register on startup. Registration should be one when the `Gson` instance is created which should be deferred to first use (and thus happen on a background thread).

I would argue that's the bug here, not necessarily the use of reflection.

**Comment by solcott** [comment]
Thanks for the feedback,  I have switched my application to lazily create gson on first use in a background thread.
