### ISSUE TITLE
RuntimeException: Unable to pre-dex

### ISSUE THREAD

**Issue by RiccardoM** [rharter/auto-value-gson#131]
Hi @rharter, first of all thanks for the good job you've done, I really appreciate it.

I was working with A-v-g and I found what I think that might be a bug. 

I have the following modules' architecture (requested by GreenDao):

```
|- app
|- core
|- greendao-schema-generator
```

where `app` and `core` are both Android modules, while `greendao-schema-generator` is a plain-Java module with the relative `apply plugin: 'java'` text inside. 

I've added your library to my `core` module like follows: 

```
compile 'com.ryanharter.auto.value:auto-value-gson:0.4.6'
annotationProcessor 'com.ryanharter.auto.value:auto-value-gson:0.4.6'
```

I know that this works becasue I've done it in another project too without any error.

When I compile the project, Android Studio does not throw any error but, however, when i try to run the built application, it throws the following error:

```
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex 'C:\Users\user\.gradle\caches\modules-2\files-2.1\com.ryanharter.auto.value\auto-value-gson\0.4.6\8e097b7d244dad42a8516a6a73c6c9b7cce0aeb6\auto-value-gson-0.4.6.jar' to 'C:\Users\user\Documents\GitHub\Zotsell Core\app\build\intermediates\transforms\dex\debug\folders\1000\10\auto-value-gson-0.4.6_ab913f482a3c135d9472812c0346b4ebda7f2918'
```

I've tried doing like it says, adding the following lines to the `build.gradle` file of the `greendao-schema-generator` module (the only one with the `java` plugin):

```
sourceCompatibility = 1.7
targetCompatibility = 1.7
```

But I had no luck and the error is still there.

Do you have any idea on why this error shows up?
Thank you in advance, and have a nice day.

**Comment by RiccardoM** [comment]
@hzsweers Any help for this?

**Comment by hzsweers** [comment]
I don't think that's anything we can help you with in this library. That's a question for the build tools team on android, maybe file a bug tracker?

**Comment by jffiorillo** [comment]
I'm having same issue, is this closed?

**Comment by bernatik** [comment]
Having the same issue when try to add firebase in app messaging dependency
