### ISSUE TITLE
New "SerializedName" annotation

### ISSUE THREAD

**Issue by d-fournier** [rharter/auto-value-gson#138]
Hi,

I'm using this AutoValue extension to avoid Gson reflection and improve the obfuscation. It is working well with some String obfuscation tools if I'm not using the SerializedName annotation. 

Unfortunately, if I need to set this annotation, as it was used at runtime by Gson, the retention type "Runtime" will leak some information. With this AutoValue extension, it is not needed anymore as it is processed at compile time.
(As far as I know, Dexguard can't obfuscate annotation values for example)

Could we create a new annotation, similar to the existing one, with an annotation without impact at Runtime ?

**Comment by JakeWharton** [comment]
Won't ProGuard strip it if you don't mark it as kept?

**Comment by d-fournier** [comment]
We are currently migrating our solution to AutoValue and we need to use the annotation on our old model classes.

Our proguard file contains :
`-keep,allowobfuscation @interface com.google.gson.annotations.*`
`-keepattributes *Annotation* `
and
```
-keepclasseswithmembers,allowobfuscation,includedescriptorclasses class * {
    @com.google.gson.annotations.SerializedName <fields>;
}
```
I think these rules prevent Proguard from removing the annotation or other rules may interfere.

**Comment by JakeWharton** [comment]
Once that's complete, though, presumably you can remove that rule and then
allow it to be stripped. I think it's a bit weird to add a separate
annotation for the use case when you're also using Gson reflectively and
also don't want the serialized name values to be retained even though they
are for the reflective version.

**Comment by hzsweers** [comment]
I agree with Jake. If you're worried about leaking information about your API in a way that could be reverse engineered, JSON I'd probably not the best conduit to use anyway

**Comment by d-fournier** [comment]
Ok, I agree with the main idea.
Thanks for the feedback
