### ISSUE TITLE
Cannot create GsonTypeAdapterFactory in library module

### ISSUE THREAD

**Issue by Fitzpasd** [rharter/auto-value-gson#139]
I cannot configure this to work when used within a library in an Android project.  Is this supported?

[Here's a minimal repo](https://github.com/Fitzpasd/AutoValueGsonAsLib) that shows my configuration.

1. Added `android-apt` to root `build.gradle`
2. Applied `android-apt` to library `build.gradle`
3. Set `apt` and `provided` as usual

**Comment by hzsweers** [comment]
it's impossible to help without a description of the error you're running into.

Possibly related - `android-apt` is deprecated and won't work with newer versions of the android gradle plugin, you should use `annotationProcessor`

**Comment by Fitzpasd** [comment]
The error is that it cannot build the concrete `@GsonTypeAdapterFactory`.

```
@GsonTypeAdapterFactory
public abstract class AutoValueGsonAdapterFactory implements TypeAdapterFactory {
    public static TypeAdapterFactory create() {
        return new AutoValue_AutoValueGsonAdapterFactory();
    }
}
```

`error: cannot find symbol class AutoValue_AutoValueGsonAdapterFactory`

Using `annotationProcessor` also doesn't work.

**Comment by hzsweers** [comment]
> Using annotationProcessor also doesn't work.

This is again too vague. Can you please elaborate? I'm hesitant to look into issues when the project uses deprecated tooling

**Comment by Fitzpasd** [comment]
If using `apt` and `provided` is considered deprecated and the collaborators of this project won't accept issues on projects that use those, [then the docs/README need to be updated](https://github.com/rharter/auto-value-gson#download).

**Comment by hzsweers** [comment]
sure we can update. `provided` is not deprecated though, just `apt`. Does updating resolve those issues though?

**Comment by wankey** [comment]
try add the code shown below to MyDTO.class.

I met the same build error , and build success after add these code to DTO CLASS
```
  public static TypeAdapter<MyDTO> typeAdapter(Gson gson) {
    return new AutoValue_MyDTO.GsonTypeAdapter(gson);
  }
```

**Comment by rharter** [comment]
Can you please check that you are trying to construct the correct generated class?  Your source shows `new AutoValue_AutoValueGsonAdapterFactory()`, but the generated class [will be prefixed](https://github.com/rharter/auto-value-gson#factory) with `AutoValueGson_`.

**Comment by Fitzpasd** [comment]
Fixing the typo doesn't solve the issue.  Pushed that change to the [repo](https://github.com/Fitzpasd/AutoValueGsonAsLib).

**Comment by rharter** [comment]
As wanky pointed out, the issue is that you haven't had AutoValueGson generate any TypeAdapters by adding a public static method returning `TypeAdapter<Foo>` to your AutoValue class, as the [documentation](https://github.com/rharter/auto-value-gson#usage) states.  

You can see a working example at https://github.com/Fitzpasd/AutoValueGsonAsLib/pull/1

**Comment by Fitzpasd** [comment]
Awesome, thanks guys!  Forgot that step.

**Comment by rpattabi** [comment]
In case anyone else is struggling, in my case my IDE imported a different `TypeAdapter` and thus faced this problem even after having the static method mentioned in the document.

It worked once I ensured the correct import i.e. `import com.google.gson.TypeAdapter`
