### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by R4md4c** [rharter/auto-value-gson#14]
Hello,

Thanks for your great extensions. 

But while trying auto-value-gson, I got an error during the build.

```
java.lang.UnsupportedClassVersionError: com/ryanharter/auto/value/gson/AutoValueGsonExtension : Unsupported major.minor version 52.0 
```

Here is my build.gradle AutoValue related content
```
final AutoValueVersion = '1.2-SNAPSHOT'
final AutoValueGson = '0.1-SNAPSHOT'
final AutoValueParcel= '0.2-SNAPSHOT'

compile "com.google.auto.value:auto-value:$AutoValueVersion"
apt "com.google.auto.value:auto-value:$AutoValueVersion"
apt "com.ryanharter.auto.value:auto-value-gson:$AutoValueGson"
apt "com.ryanharter.auto.value:auto-value-parcel:$AutoValueParcel"
```

Here is my class code
```
@AutoValue
public abstract class Partner implements Parcelable {
    public abstract String name();
    public abstract String logoUrl();
}
```

I'm using Java 7 JDK in my Android Project. And If I removed the AutoValue Gson extension, the class is generated without problems, that means I guess that the Gson extension is the problem.

**Comment by R4md4c** [comment]
I tried to add
```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
}
```

As you've advised in this isse https://github.com/rharter/auto-value-parcel/issues/5, but unfortunately it didn't fix it.

**Comment by rharter** [comment]
Have you tried with version 0.2-SNAPSOT?  It's using the correct target/source compatibility.

**Comment by R4md4c** [comment]
Thanks, It works now! I was trying the version that was in the README.md, and there weren't any other releases under the "release" tab, so I wasn't aware about the new version.

**Comment by rharter** [comment]
Thanks, I've updated the readme accordingly.
