### ISSUE TITLE
Boolean: is naming convention: Cannot find symbol

### ISSUE THREAD

**Issue by PaulWoitaschek** [rharter/auto-value-gson#15]
I have a very simple class:

```java
@AutoValue public abstract class PurchaseStateModel {

    @NonNull public static PurchaseStateModel of(boolean isPurchased) {
        return new AutoValue_PurchaseStateModel(isPurchased);
    }

    public abstract boolean isPurchased();
}
```

Which causes an exception at compile time. It transformed "isPurchased" to "purchased".

```java
@Override
    public void write(JsonWriter jsonWriter, PurchaseStateModel object) throws IOException {
      jsonWriter.beginObject();
      jsonWriter.name("purchased");
      purchasedAdapter.write(jsonWriter, object.purchased());
      jsonWriter.endObject();
    }
```

**Comment by rharter** [comment]
This is because the `is` prefix is a common prefix, like `get`, for java properties, so AutoValue strips common Java property prefixes.

You can fix this by simply using Gson's `@SerializedName` attribute to tell it you actually do want the serialized version called `isPurchased`.

**Comment by JakeWharton** [comment]
Are you sure it's not this bug which I fixed in the parcel impl? https://github.com/rharter/auto-value-parcel/commit/cdba2d9a1c9e5c3dc0ed5d373b51afe28104af87

**Comment by rharter** [comment]
You're right.  Sorry, I thought the error was in the JSON naming, not the method name.  That makes sense now.

**Comment by PaulWoitaschek** [comment]
Thanks :+1:
