### ISSUE TITLE
auto-value-gson kills auto-value 1.5.1

### ISSUE THREAD

**Issue by ChristianCiach** [rharter/auto-value-gson#152]
When using these annotation processors in Eclipse, auto-value completely stops working for me.

Is auto-value-gson not compatible with auto-value 1.5?

**Comment by bejibx** [comment]
Working fine in my projects. I'm using auto-value-gson 0.6.0, autovalue 1.5.1 and AndroidStudio.

**Comment by hzsweers** [comment]
works fine here too. Your issue is hard to diagnose without more details

**Comment by ChristianCiach** [comment]
I don't know what we've changed on our side, but it's working for us now, too. I am sorry for creating this issue :)
