### ISSUE TITLE
Seeking help in regarding to Compiler options on Java Project

### ISSUE THREAD

**Issue by TonyTangAndroid** [rharter/auto-value-gson#154]
I do realize that there is possibility to configure [Compile Option](https://github.com/rharter/auto-value-gson#compiler-options) in Android Project. 
For example, I could make the following configuration in an Android Project to **generate default setter method**.

 

    defaultConfig {
        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath false
                arguments = ['autovaluegson.mutableAdaptersWithDefaultSetters': 'true']
            }
        }
    }
 

However, I do not know how to make it applicable on a Java Project.  I had tried to google it online but get no luck. Any help or hint would be appreciated.

**Comment by JakeWharton** [comment]
You can look up the JavaCompile task and then add to its compilerArgs the
options starting with -A. Like "-Afoo=bar".

**Comment by TonyTangAndroid** [comment]
Thanks a lot for the hint.  It works perfect. Here is the snippet just in case anyone else who is wondering.

```
apply plugin: 'java'
compileJava {
    options.compilerArgs << '-Aautovaluegson.mutableAdaptersWithDefaultSetters=true'
}

```

**Comment by JakeWharton** [comment]
Great. I was mobile or I would have given you a more copy/paste example!

**Comment by TonyTangAndroid** [comment]
No worry at all. It could better help me.  AND You are just everywhere. LoL
