### ISSUE TITLE
GenerateTypeAdapter proguard warning

### ISSUE THREAD

**Issue by xdgimf** [rharter/auto-value-gson#162]
Updated to 0.7.0 and got this proguard warnings related to the new annotation `@GenerateTypeAdapter`. I haven't used it yet so I'm not really sure.

Here's the proguard warning
```
Warning: library class com.ryanharter.auto.value.gson.GenerateTypeAdapter$1 extends or implements program class com.google.gson.TypeAdapterFactory

Warning: there were 1 instances of library classes depending on program classes.
         You must avoid such dependencies, since the program classes will
         be processed, while the library classes will remain unchanged.
```

Here's my dependencies
```
depedencies {
    //...
    compileOnly "com.jakewharton.auto.value:auto-value-annotations:$project.ext.autoValueAnnotationsVersion"
    compileOnly "com.ryanharter.auto.value:auto-value-gson:$project.ext.autoValueGsonVersion"
    annotationProcessor "com.google.auto.value:auto-value:$project.ext.autoValueVersion"
    annotationProcessor "com.ryanharter.auto.value:auto-value-gson:$project.ext.autoValueGsonVersion"
    annotationProcessor "com.ryanharter.auto.value:auto-value-parcel:$project.ext.autoValueParcelVersion"
    //...
    implementation "com.google.code.gson:gson:$project.ext.gsonVersion"
    //...
}
```

For now I simply ignored the warnings by adding the following rules:
```
-dontwarn com.ryanharter.auto.value.gson.GenerateTypeAdapter
-dontwarn com.google.gson.TypeAdapterFactory
```

Edit: Added Gson dependency

**Comment by JakeWharton** [comment]
Do you have a Gson dependency?

**Comment by xdgimf** [comment]
Yes, I have a Gson dependency.

**Comment by adin234** [comment]
any updates on this?

**Comment by hzsweers** [comment]
Only thing I can think of is that proguard is complaining that there's code in the annotations artifact that isn't there at runtime because you're not compiling the annotations. There's a full TypeAdapterFactory implementation in the GenerateTypeAdapter annotation code

**Comment by hzsweers** [comment]
Closing this out, but the rules above should suffice. Unfortunately we can't solve this with an embedded proguard file as these would be compileOnly and presumably not reach proguard/R8 tools to index on
