### ISSUE TITLE
Error on usage of GsonTypeAdapterFactory when there are no generated TypeAdapters.

### ISSUE THREAD

**Issue by NightlyNexus** [rharter/auto-value-gson#171]
I was adding a `@GsonTypeAdapterFactory` today and couldn't figure out why my `AutoValueGson_JsonAdapterFactory` was not being generated.
```java
@GsonTypeAdapterFactory
public abstract class JsonAdapterFactory implements TypeAdapterFactory {
  public static TypeAdapterFactory create() {
    return new AutoValueGson_JsonAdapterFactory();
  }
}
```

I later realized that none of my AV models (which are themselves generated by another tool), had included the static `jsonAdapter(Gson gson)` methods.

Would it be possible to check for `@GsonTypeAdapterFactory` usage when there is no TypeAdapterFactory to generate? (same question for av-moshi.)

**Comment by rharter** [comment]
Is there no warning emitted? I thought we had done that a while ago (on the
phone, so hard to double check)

**Comment by okorz001** [comment]
I ran into this problem today. There is no specific warning emitted from auto-value-gson. The compiler will just complain that the generated class does not exist (cannot find symbol).

I did not realize that I still needed to add the static TypeAdapter methods to every class when using the GsonTypeAdapterFactory until I saw this issue.

**Comment by Andranik-Asilbekyan** [comment]
Today I got the same error(AutoValueGson_MyAdapterFactory was not generated).
  
`@GsonTypeAdapterFactory
public abstract class MyAdapterFactory implements TypeAdapterFactory {

    public static TypeAdapterFactory create() {
        return new AutoValueGson_MyAdapterFactory();
    }
}
`
Error log:
`Caused by: java.lang.NoClassDefFoundError: com/google/auto/value/AutoValue
	at com.ryanharter.auto.value.gson.AutoValueGsonAdapterFactoryProcessor.getSupportedAnnotationTypes(AutoValueGsonAdapterFactoryProcessor.java:61)
....
Caused by: java.lang.ClassNotFoundException: com.google.auto.value.AutoValue
`

**Comment by nksaroj** [comment]
java.lang.NoClassDefFoundError: com/google/auto/value/AutoValue same here

**Comment by liujoshua** [comment]
Hello, I think I may have found a fix for one case. When using multiple, interdependent modules with @AutoValue classes, I was also seeing ```java.lang.NoClassDefFoundError: com/google/auto/value/AutoValue```

```
   annotationProcessor 'com.ryanharter.auto.value:auto-value-gson:0.7.0'
   annotationProcessor 'com.google.auto.value:auto-value-annotations:1.6' // include again for auto-value-gson
```

Not sure why this is happening! I see that auto-value-gson already includes auto-value-annotations as an API dependency: https://github.com/rharter/auto-value-gson/blob/a264e19063f271f7166ea59b0202f78b854342f1/auto-value-gson/build.gradle#L14

@nksaroj @Andranik-Asilbekyan

**Comment by jffiorillo** [comment]
@liujoshua How do you solve it ? I have a similar case, multiples interdependent modules!

**Comment by jffiorillo** [comment]
@liujoshua (or anyone) know why adding the `auto-value-annotations` as `annotationProcessor` solve the issue ?

**Comment by okmanideep** [comment]
why is this added as an `api` dependency for the annotationProcessor?
https://github.com/rharter/auto-value-gson/blob/a264e19063f271f7166ea59b0202f78b854342f1/auto-value-gson/build.gradle#L13

**Comment by jffiorillo** [comment]
@okmanideep It contains the interfaces ( ex:  @interface AutoValue ) to be used by the annotationProcessor.

**Comment by francais-harry** [comment]
Not sure but maybe related topic? https://github.com/rharter/auto-value-moshi/issues/106

**Comment by zsweigart** [comment]
This also fails when you have the autovalue classes in a different module than your type adapter
