### ISSUE TITLE
Add support for custom JsonSerializer and JsonDeserializer

### ISSUE THREAD

**Issue by rubixhacker** [rharter/auto-value-gson#173]
Gson 2.8.1 add the ability to provide an object in the `@JsonAdapater` that implemented JsonSerializer and/or JsonDeserializer. Right now `@GsonTypeAdapter` only accepts TypeAdapters. It would be great if GsonTypeAdapter was expanded to accept JsonSerializer/JsonDeserializer or a new annotation was added to support this.

**Comment by hzsweers** [comment]
For the sake of keeping things simple, I think we're going to keep it at just `TypeAdapter`s for now. PRs welcome
