### ISSUE TITLE
Add support for incremental annotation processing with Gradle 4.7

### ISSUE THREAD

**Issue by simtel12** [rharter/auto-value-gson#179]
Same as rharter/auto-value-parcel#131: As Gradle 4.7 is out, there had to be an issue for this :)
The documentation to handle this is [here](https://docs.gradle.org/4.7/userguide/java_plugin.html#sec:incremental_annotation_processing).

I think auto-value-gson could implement this? (but I might be wrong as I don't fully understand all the works behind annotation processors).

**Comment by 3flex** [comment]
May be worth waiting to see what happens in auto value first... https://github.com/google/auto/issues/615

**Comment by bingranl** [comment]
Auto Value supports incremental annotation processing in 1.6.3-rc1. Extension can implement new API to support incremental annotation processing. See #673
