### ISSUE TITLE
Add support for field naming policies

### ISSUE THREAD

**Issue by suyash192** [rharter/auto-value-gson#18]
Gson has support for different field naming policies which does not seem to work with this library. For example, by setting LOWER_CASE_WITH_UNDERSCORES while creating the gson object, all field names with lowercase and underscore separated format will automatically mapped to their camel case formats in the Java classes.

```
Gson gson = new GsonBuilder()
    .setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
    .create();

public class Dog {
    public String makeNoise;
}
```

**And its equivalent json:**

```
{
    "make_noise": "bark"
}
```

We can use @SerializedName annotation for this but it becomes tedious if all the field names are to be converted from the same underscore format.

**Comment by rharter** [comment]
I agree this, in addition to the date format, etc, would be useful to have automatically handled in the generated TypeAdapterFactory.

Unfortunately, the FieldNamingPolicy that's set in the `GsonBuilder` is not available, so I think the only real option we have is to add an optional constructor to the generated TypeAdapterFactory that takes these settings, or a config object containing them.

```java
Gson gson = new GsonBuilder()
  .setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
 .registerTypeAdapterFactory(
    Foo.typeAdapterFactory(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES))))
  .build();
```

This, obviously, can get quite unweildy, but could be reduced by the solution in issue #19.

**Comment by Maragues** [comment]
@rharter have you tried that solution? I can't make it work

This is my TypeAdapterFactory 
```
public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
    Class<? super T> rawType = type.getRawType();
    if (rawType.equals(Foo.class)) {
      return (TypeAdapter<T>) Foo.typeAdapter(new GsonBuilder()
.setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
.create());
    }
    return null;
  }
```

Thanks!

**Comment by rharter** [comment]
Yeah, the one in Gson.factories is used internally, but isn't available to custom TypeAdapters, IIRC.  Even if it was, we'd have to update the generated TypeAdapter to use it.

**Comment by Maragues** [comment]
Then there's no way to use a custom *FieldNamingPolicy*? That's a blocking issue for those of us that do need it.

Thanks anyway for your time, I'll keep an eye on this issue hoping that it gets fixed soon.

**Comment by rharter** [comment]
@Maragues I just submitted a PR to Gson to support this.

**Comment by Maragues** [comment]
Wow, that was quick! Let's see how that works out.

**Comment by Maragues** [comment]
@rharter I guess this is blocked until Gson publishes a new stable release. Will it be fixed easily once they do? 

I've been avoiding the issue up until now, but I guess I'll need to fork the repo and force the fieldNamingPolicy

**Comment by rharter** [comment]
yeah, should be fairly straightforward once that's up

**Comment by JakeWharton** [comment]
We finally got around to releasing Gson 2.7... 🎉

**Comment by Rashwan** [comment]
No news about a fix for this issue ?

**Comment by Maragues** [comment]
For now I'm overriding AutoValue's abstract generated methods and using @SerializedName annotation. It's ugly and adds unnecessary code lines, but it works until this issue is fixed

 ```
 @Override
 @SerializedName("full_name")
 public abstract boolean fullName();
```

**Comment by cushon** [comment]
What will the generated code for this look like? FieldNamingPolicy expects `java.lang.reflect.Field`s, so will the generated code have to look up the fields reflectively and keep track of the mapping at runtime?

It'd be nice if there was a way to configure the policy statically, and preserve the current string switch code.

**Comment by michaelcarrano** [comment]
Just wondering if there has been any progress on this issue?

**Comment by rafakob** [comment]
Any news? It feels like auto value is not so great after all...

**Comment by hzsweers** [comment]
Maragues' [answer](https://github.com/rharter/auto-value-gson/issues/18#issuecomment-247587803) is the correct one IMO. I don't see why auto-value-gson needs to take an opinion on this.

**Comment by 3flex** [comment]
ICYMI: I opened #124 as a proposal to add this feature, appreciate any feedback.

Biggest limitation (or feature?) is that it doesn't use reflection, so can't handle arbitrary `FieldNameStrategy`s, but it does support all the built in `FieldNamePolicy`s that Gson provides.

**Comment by Ajibola** [comment]
@rharter seems your PR to google/gson has been merged to 2.8.1. When can the impl for TypedAdapter be made to enable setting field name strategy?

**Comment by hzsweers** [comment]
I'm pretty against av-gson taking an opinion here when you can just annotate parameters. This feature of gson in general was always a bit weird to me since it's pretty best effort

**Comment by Ajibola** [comment]
hzsweers  it is a convenient tool for auto mapping the names instead of writing serialized annotations, which makes the class less readable i think.

**Comment by hzsweers** [comment]
why not have your backend send you nicer keys? Also - the only thing you need to read are your methods when using the model code from elsewhere, the annotations are an implementation detail, I don't know what readability has to do with it
