### ISSUE TITLE
Move AutoValueGsonExtensionTest.java "expected" output to separate files

### ISSUE THREAD

**Issue by 3flex** [rharter/auto-value-gson#181]
I'm probably just not doing things all that efficiently and there may be a better way, but I'm finding it extremely tedious to modify AutoValueGsonExtensionTest.java for my PR to reflect expected output because of the string concatenation, escaping and manually inserting newlines. I'm sure I can change my IDE's settings to reflect the way it's handled in the test file, but to me it seems simpler to just reference a file that just contains the raw expected output? Copy/pasting from the test report when expected doesn't match actual generated source would make things much easier.

**Comment by ZacSweers** [comment]
I think we should just stop using compile-testing for anything other than testing expected build errors, and move the rest to integration tests in the sample project's tests. These are exceedingly difficult to maintain in their current form and what we really care about is functionality, which the current tests don't actually test!

**Comment by ZacSweers** [comment]
Closing this out for now as we've started setting up integration tests. I don't think there's too much impetus to move one way or the other right now
