### ISSUE TITLE
JSON field annotation

### ISSUE THREAD

**Issue by ming13** [rharter/auto-value-gson#2]
If it is not possible to use the `SerializedName` annotation from Gson itself, why not use something (probably) better named? Like `Json` from Moshi.

![giphy](https://cloud.githubusercontent.com/assets/200401/9461503/de55d426-4b17-11e5-9aa9-d8738e1ed8de.gif)

**Comment by JakeWharton** [comment]
https://github.com/google/gson/pull/688

**Comment by ming13** [comment]
Great!
