### ISSUE TITLE
Possible to extend the deserializer to add additional custom value decoding?

### ISSUE THREAD

**Issue by laurencedawson** [rharter/auto-value-gson#20]
Hi,
In my use case I have an auto-value object with that looks something like:

class Foo {
  String a;
  String b;
  String c;
  String d;
  CustomObject e;
}

I'd like to extend the auto-value deserializer to automatically parse a,b,c,d but let me add additional logic to manually parse the CustomObject at the end.

Is this possible?

Thanks

**Comment by rharter** [comment]
To accomplish this you would create a Gson [TypeAdapter](https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/TypeAdapter.html) and add it to your GsonBuilder. The TypeAdapter that AutoValue: Gson generated will use that behind the scenes.

**Comment by rharter** [comment]
The custom type adapter would be for `CustomObject` and can be outside of the AutoValue class.

**Comment by laurencedawson** [comment]
Thanks I'll look into that.

Is it also possible to override the parsing for a specific built in type?

e.g. For "String a" I'd like to perform some processing from the text in the JSON before assigning it to String a
