### ISSUE TITLE
Compilation error if AutoValue class has toBuilder method

### ISSUE THREAD

**Issue by ViTORossonero** [rharter/auto-value-gson#21]
If _AutoValue_ class has _toBuilder_ method to initialize a builder to the same property values as an existing value instance([#to_builder](https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#to_builder)), generated constructor for _AutoValue_CommentModel_ has one redundant parameter: _CommentModel.Builder toBuilder_

Example:

```
@AutoValue
public abstract class CommentModel {
    ...
    public abstract Builder toBuilder();
    ...
```
Generated class:
```
final class AutoValue_CommentModel extends $AutoValue_CommentModel {
    AutoValue_CommentModel(..., CommentModel.Builder toBuilder) {
        super(..., toBuilder);
    }
...
```

**Comment by rharter** [comment]
This is a known issue in the base AutoValue project tracked by issue [#281](https://github.com/google/auto/issues/281).  Check that issue for a workaround until they fix it.

**Comment by rharter** [comment]
Sorry, that issue doesn't contain the workaround.  The workaround is to simply implement the `toBuilder()` method:

```java
public Builder toBuilder() {
  return return new AutoValue_Foo.Builder(this);
}
```

**Comment by ViTORossonero** [comment]
Ok, thanks.
