### ISSUE TITLE
"autovaluegson.mutableAdaptersWithDefaultSetters" not working.

### ISSUE THREAD

**Issue by bardyamomeni** [rharter/auto-value-gson#212]
Hi,

We updated to 1.0.0, but apparently the processor option "autovaluegson.mutableAdaptersWithDefaultSetters" does not work anymore?
how can we generate default setters for the type adapters in 1.0.0?

Thanks

**Comment by ZacSweers** [comment]
Per the release notes, this support was removed in 1.0
