### ISSUE TITLE
support default value for generated type adapter 

### ISSUE THREAD

**Issue by efraimg** [rharter/auto-value-gson#218]
I would like to add a none nullable new field so will be helpful to be able to set a default value in the deserializer. I see that in older versions it was available but can't see it on 1.0.0.
Is it possible to achieve this somehow?

**Comment by ZacSweers** [comment]
We removed it and feel it's something that should be handled via #136, but requires support from autovalue

**Comment by efraimg** [comment]
Thank you:)

**Comment by otto-dev** [comment]
For anyone else looking, this has been implemented in #224.Update to 1.1.x
