### ISSUE TITLE
auto-value-gson-from-rharter-generated-invalid-code

### ISSUE THREAD

**Issue by CodeMasterMo** [rharter/auto-value-gson#252]
We are using https://github.com/rharter/auto-value-gson to generate the TypeAdapter for our @AutoValue objects. 

For Animal class

@AutoValue
abstract class Animal {
    abstract String name();

    abstract int numberOfLegs();

    static Builder builder() {
        return new AutoValue_Animal.Builder();
    }

    public static TypeAdapter<Animal> typeAdapter(Gson gson) {
        return new AutoValue_Animal.GsonTypeAdapter(gson);
    }

    @AutoValue.Builder
    abstract static class Builder {
        abstract Builder setName(String value);

        abstract Builder setNumberOfLegs(int value);

        abstract Animal build();
    }
}
The code is generated with this part at the end

@Override
    @SuppressWarnings("unchecked")
    public Animal read(JsonReader jsonReader) throws IOException {
...
..

     jsonReader.endObject();
      return builder.abstract com.project.Animal build();
}
Shouldn't this be builder.build();

We are using eclipse to build the code and compile to java 8.

Does anyone has any tips how to solve this?

**Comment by mseele** [comment]
@rharter i've added a PL to fix this issue. Would you mind to release a new version?

**Comment by mseele** [comment]
@rharter thank's for applying the pl. Is there any timeline you will release a new version (1.4?) and push it to maven repositories?

**Comment by rharter** [comment]
You should see 1.3.1 in central.

**Comment by mseele** [comment]
> You should see 1.3.1 in central.

I don't see it
- https://repo1.maven.org/maven2/com/ryanharter/auto/value/auto-value-gson-extension/
- https://mvnrepository.com/artifact/com.ryanharter.auto.value/auto-value-gson-extension/

Am I looking on the wrong repositories?

**Comment by rharter** [comment]
Sorry about that, @mseele, I must've gotten distracted.  It's syncing up now.

**Comment by mseele** [comment]
@rharter There is only a 1.3.1 in central for [auto-value-gson-runtime](https://repo1.maven.org/maven2/com/ryanharter/auto/value/auto-value-gson-runtime/), but my fix was in [auto-value-gson-extension](https://repo1.maven.org/maven2/com/ryanharter/auto/value/auto-value-gson-extension/). Would you mind release a 1.3.1 for auto-value-gson-extension, too? Thank you!
