### ISSUE TITLE
What dependency AutoValue annotation is in ?

### ISSUE THREAD

**Issue by unoexperto** [rharter/auto-value-gson#255]
What dependency `@AutoValue` annotation is in ?

I added these

```
    implementation("com.google.code.gson:gson:2.8.6")
    implementation("com.ryanharter.auto.value:auto-value-gson-runtime:1.3.0")
    kapt("com.ryanharter.auto.value:auto-value-gson-extension:1.3.0")
    kapt("com.ryanharter.auto.value:auto-value-gson-factory:1.3.0")
```

They won't have it :(

**Comment by ZacSweers** [comment]
it is in the auto value annotations project, which this depends on

**Comment by unoexperto** [comment]
@ZacSweers Sorry, still no joy :( Which dependency exactly? This one https://mvnrepository.com/artifact/com.ryanharter.auto.value/auto-value-gson-annotations/0.8.0 ?
