### ISSUE TITLE
How would I go about using an ExclusionStrategy of a custom annotation targeted to a Field?

### ISSUE THREAD

**Issue by muddin1** [rharter/auto-value-gson#27]
Trying to do something along the lines of:

``` java
    // The fields I want to exclude from serialization/deserialization 
    @Documented
    @Retention(RetentionPolicy.RUNTIME)
    @Target({ElementType.FIELD, ElementType.METHOD}) // FIXME: remove method
    public @interface Exclude {
    }
```
``` java
    public static class ExcludeAnnotationExclusionStrategy implements ExclusionStrategy {
        @Override
        public boolean shouldSkipField(FieldAttributes f) {
            return f.getAnnotation(Exclude.class) != null;
        }

        @Override
        public boolean shouldSkipClass(Class<?> clazz) {
            return false;
        }
    }
```
``` java
    Gson gson = new GsonBuilder()
            .registerTypeAdapterFactory(new AutoValueTypeAdapterFactory())
            .serializeNulls()
            .setExclusionStrategies(new ExcludeAnnotationExclusionStrategy())
            .create();
```

I tried simply implementing the derived property style where I define the field in the abstract class with its own accessor method and annotate this property with `@Exclude`, but this doesn't work as it is not included in the generated `GsonTypeAdapter`. Also, it will not be included in the generated parcelable implementation using `auto-value-parcel`.

**Comment by rharter** [comment]
The exclusion strategy in your example is used by Gson in the [ReflectiveTypeAdapterFactory](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/internal/bind/ReflectiveTypeAdapterFactory.java), which isn't used with AutoValue, since auto-value-gson generates it's own TypeAdapter for the type.

To accomplish this, we'd have to create an annotation to be used by auto-value-gson to manually exclude certain parameters from the type adapter.

**Comment by heutschibogdan** [comment]
Do you plan on adding such an annotation?

**Comment by rharter** [comment]
This will be solved when #18 is fixed.

**Comment by Rainer-Lang** [comment]
@rharter gson 2.7 is out. How to exclude fields? Could you give a hint?

**Comment by Maragues** [comment]
@Rainer-Lang #18 hasn't been fixed yet. Once the original Gson is used by the generated TypeAdapter, we can implement a solution such as the one created by @muddin1 

I'm also really looking forward to the fix, let's hope @rharter has the time or someone picks it up

**Comment by zoopolitic** [comment]
So there is no way to exclude some field from serialization/deserialization using this gson extension atm ?
