### ISSUE TITLE
Serializing null AutoValue object

### ISSUE THREAD

**Issue by niqo01** [rharter/auto-value-gson#28]
I am converting slowly my value objects to AutoValue with Gson extension.
I am having an issue for the following case:
(Pseudo code)
```
// Not an AutoValue (yet)
class A{
 B b;
}

@AutoValue
class B{
  public abstract Boolean enabled();

  public static TypeAdapter<B> typeAdapter(Gson gson) {
    return new AutoValue_B.GsonTypeAdapter(gson);
  }
}
```
When I am trying to serialize A with gson and B is null I am getting a NPE on the following line `if (object.enabled() != null)` inside $AutoValue_B:
```
    @Override
    public void write(JsonWriter jsonWriter, B object) throws IOException {
      jsonWriter.beginObject();
      if (object.enabled() != null) {
        jsonWriter.name("enabled");
        enabledAdapter.write(jsonWriter, object.enabled());
      }
      jsonWriter.endObject();
    }
```
because `object` is null.

**Comment by JakeWharton** [comment]
Call .nullSafe() on the TypeAdapter before registering it.

**Comment by JakeWharton** [comment]
Keep in mind it returns a new null-safe instance which needs registered,
not modifies the existing one.

**Comment by niqo01** [comment]
Thanks @JakeWharton. I missed that useful API.
