### ISSUE TITLE
Would be useful to restrict serialization/deserialization with gson @Expose annotation

### ISSUE THREAD

**Issue by sschendel** [rharter/auto-value-gson#34]
We conditionally expose fields in our models with the `@Expose` annotation.  GsonBuilder can be configured to recognize.  Is there a plan to enable this feature with auto-value-gson extension?

```
public class MyModel {
   private long doNotExpose;   
  @Expose @SerializedName("expose_me") private long exposeMe;  
...
}
```

```
final Gson gson = new GsonBuilder()
   .excludeFieldsWithoutExposeAnnotation()
...
   .create();
```

**Comment by rharter** [comment]
This will be taken care of when #18 is solved.

**Comment by Rainer-Lang** [comment]
@rharter If you have to guess....when do you think this is "solved"?

**Comment by rharter** [comment]
Just waiting on a PR in the gson repo to be released.  It just got merged, so shouldn't be too long.

**Comment by Rainer-Lang** [comment]
@rharter Thanks for answer. I was a bit afraid because it is a PR of google/auto........
