### ISSUE TITLE
Add support for custom TypeAdapters

### ISSUE THREAD

**Issue by Maragues** [rharter/auto-value-gson#44]
I need to modify some fields before sending my objects and after parsing them. More precisely, I convert from epoch seconds to epoch milliseconds and viceversa.

Before adding auto-value I was using custom TypeAdapters to do this conversion, but I can't do that anymore, since *AutoValue_Foo.GsonTypeAdapter* is final.

**Comment by troyjperales** [comment]
Return whichever TypeAdapter you would like to use in your typeAdapter method:
```
public static TypeAdapter<Foo> typeAdapter(Gson gson) {
        return new TypeAdapter<Foo>() {
            @Override
            public void write(JsonWriter out, Foo value) throws IOException {
                // ...
            }

            @Override
            public Foo read(JsonReader in) throws IOException {
                // ...
            }
        };
    }
```

**Comment by Maragues** [comment]
Thanks @troyjperales , but the sole point of this library is to create TypeAdapters for AutoValue objects. If I use my own implementation of TypeAdapter, I may as well not use the library.

**Comment by Maragues** [comment]
@rharter Is there a good reason for GsonTypeAdapters to be final? I'd be happy to send a PR removing the final

**Comment by Maragues** [comment]
Well, truth is I don't need this anymore, but maybe others will
