### ISSUE TITLE
Ignore(BOTH) isn't respected

### ISSUE THREAD

**Issue by shalzz** [rharter/auto-value-gson#48]
Provide an annotation that lets us specify the fields _not_ to be included in the generated TypeAdapter for the `@AutoValue` annotated class.

For Example:

``` java
@AutoValue public abstract class Foo {
  @Gson.Ignore abstract String bar();
  @SerializedName("Baz") abstract String baz();

  // The public static method returning a TypeAdapter<Foo> is what
  // tells auto-value-gson to create a TypeAdapter for Foo.
  public static TypeAdapter<Foo> typeAdapter(Gson gson) {
    return new AutoValue_Foo.GsonTypeAdapter(gson);
  }
}
```

Generated Class:

``` java
public static final class GsonTypeAdapter extends TypeAdapter<Foo> {
    private final TypeAdapter<String> bazAdapter;
    public GsonTypeAdapter(Gson gson) {
      this.bazAdapter = gson.getAdapter(String.class);
    }

   // ...
}
```

**Comment by Shalzz** [comment]
Just saw your comment in #27 , keep this open till support for it is added?

**Comment by eliasbagley** [comment]
What's the status on this? I need to be able to ignore certain fields from being serialized

**Comment by aegis123** [comment]
you can use `@Ignore(SERIALIZATION)`, `@Ignore(DESERIALIZATION)` or `@Ignore(BOTH)` to ignore abstract methods from typeadapter creation.

**Comment by ubuntudroid** [comment]
@aegis123 Unfortunately BOTH doesn't work as it isn't checked for.

**Comment by aegis123** [comment]
@ubuntudroid sorry my mistake `BOTH` is the default option for `@Ignore` so you don't have to specify it.

**Comment by hzsweers** [comment]
I cannot repro this, so feel free to re-open with a repro code example. The test for this is pretty comprehensive as well. I am making some minor cleanups to the logic in #196
