### ISSUE TITLE
Support toBuilder method

### ISSUE THREAD

**Issue by ansf** [rharter/auto-value-gson#49]
AutoValue-gson generates a class which does not compile when I have a `toBuilder` method in my class. It seems to confuse it for a property and generates an constructor for it:

```
@AutoValue public abstract class Foo {

    abstract long id();

    public static TypeAdapter<Foo> typeAdapter(Gson gson) {
        return new AutoValue_Foo.GsonTypeAdapter(gson);
    }

    abstract Builder toBuilder();

    @AutoValue.Builder
    static abstract class Builder {
        abstract Builder id(long id);
        abstract Foo build();
    }
}
```

**Comment by rharter** [comment]
This is a [known issue](https://github.com/google/auto/issues/281) in auto value that has been fixed but not yet released. It will be solved in the next release.

**Comment by ansf** [comment]
Oh that's good. Thanks!
