### ISSUE TITLE
Android studio multiple modules and Generated TypeAdapterFactory

### ISSUE THREAD

**Issue by muddin1** [rharter/auto-value-gson#51]
I've been using AutoValueGson 0.2.5 in my android project which consists of two modules **A** and **B**. **B** has a compile dependency on **A**, and both **A** and **B** contain AutoValue classes.

I created two `TypeAdapterFactory`s for both the modules: **AFactory** and **BFactory**. I, however, made **BFactory** extend **AFactory** so I could use it in `GsonBuilder.registerTypeAdapterFactory(new BFactory())` and have all my AutoValue typeAdapters included.

The idea is that I can have module **A** be used by a certain module **C** and follow the same pattern.

I am not sure how 0.3.0's generated `AutoValueGsonTypeAdapterFactory`s in both modules can accommodate what I was doing with a custom Factory class.

**Comment by hai-nguyen** [comment]
+1. We experienced the same issue

**Comment by rharter** [comment]
Does the 0.4.0 update solve this issue for you? Inheritance won't work (use composition instead!) but you can now have a generated TypeAdapterFactory for each module without conflict.

**Comment by rharter** [comment]
I'm closing this since it should be solved with the approach taken in 0.4.0.  Please reopen this issue if it's not solved.

**Comment by muddin1** [comment]
This si great with Composition. Thanks.
