### ISSUE TITLE
Add apt option for not generated AutoValueGsonTypeAdapterFactory

### ISSUE THREAD

**Issue by darktiny** [rharter/auto-value-gson#55]
For some reason, we generated `AutoValueGsonTypeAdapterFactory` ourselves.

**Comment by rharter** [comment]
If you just don't include the static method returning the `TypeAdapter` it won't be generated.  Though I don't know offhand how you'd get your TypeAdapter, so perhaps that's not the best approach.

**Comment by darktiny** [comment]
For our use case, all `@AutoValue` annotated class will need `TypeAdapter`. So in our own `AnnotationProcessor`, we will check if the static method returning the `TypeAdapter` exist. If not, build will failed. Otherwise, generated `AutoValueGsonTypeAdapterFactory ` ourselves.

as you said:
> If you just don't include the static method returning the TypeAdapter it won't be generated.

`auto-value-gson` could not provide that check

**Comment by darktiny** [comment]
https://github.com/rharter/auto-value-gson/issues/58 We also use `auto-value-gson` for multi modules

**Comment by junqinghaha** [comment]
https://github.com/rharter/auto-value-gson#factory
Create by yourself
