### ISSUE TITLE
Add @SuppressWarnings to AutoValueGsonTypeAdapterFactory's method create

### ISSUE THREAD

**Issue by igoticecream** [rharter/auto-value-gson#57]
Hello, I'm getting compilation warnings about unchecked or unsafe casts whenever i use your library.

I did a pull request about what need to be changed but travis gives error on test, and it's ok because generated files changes.

Anyways, please consider add these lines to AutoValueGsonAdapterFactoryProcessor, under MethodSpec.Builder create = MethodSpec.methodBuilder("create"):

.addAnnotation(AnnotationSpec.builder(SuppressWarnings.class)
                    .addMember("value", "$S", "unchecked")
                    .build())

**Comment by hzsweers** [comment]
This was actually done in #59
