### ISSUE TITLE
AutoValueGsonAdapterFactoryProcessor doesn't account for projects with multiple modules

### ISSUE THREAD

**Issue by solcott** [rharter/auto-value-gson#58]
AutoValueGsonAdapterFactoryProcessor generated a class called com.ryanharter.auto.value.gson.AutoValueGsonTypeAdapterFactory.  This obviously doesn't work when auto-value-gson is used in multiple modules.  It would be nice if auto-value-gson would either allow modules to change the package/class name via an annotation processor argument or have some other way to workaround this.

**Comment by muddin1** [comment]
https://github.com/rharter/auto-value-gson/issues/52

**Comment by fdlk** [comment]
How should I use this in multi-module (maven) project? Should I generate a factory for each module and register all of them separately? From the documentation this is not clear to me.

> To generate a TypeAdapterFactory for all of your auto-value-gson classes, simply create an abstract class that implements TypeAdapterFactory and annotate it with @GsonTypeAdapterFactory, and auto-value-gson will create an implementation for you. You simply need to provide a static factory method, just like your AutoValue classes, and you can use the generated TypeAdapterFactory to help Gson de/serialize your types.

**Comment by gengjiawen** [comment]
Looks like we need generate and register in every module, which is a little cumbersome.

**Comment by hzsweers** [comment]
This is a limitation of javac. You can't read annotated elements from already-compiled classes during your project's processing.

**Comment by rharter** [comment]
There is a library (coming? @hzsweers) from Uber that can help with this,
but as @hzsweers said, since have runs independently on each module there's
nothing we can do about it, you would have to generate one for each module
and coalesce them somewhere.
