### ISSUE TITLE
parameterized types

### ISSUE THREAD

**Issue by UnknownUntilNow** [rharter/auto-value-gson#6]
code with parameterized types, for example a Map results in:
           gson.getAdapter(Map\<String, String\>.class).write(jsonWriter, object.map());
and
           map = gson.getAdapter(Map\<String, String\>.class).read(jsonReader);
which results in a compile time error

**Comment by JakeWharton** [comment]
#5 should fix this.

**Comment by UnknownUntilNow** [comment]
fixes it, but it is not uploaded to the sonatype repository

**Comment by rharter** [comment]
This has been pushed.
