### ISSUE TITLE
GsonTypeAdapterFactory not found

### ISSUE THREAD

**Issue by epool** [rharter/auto-value-gson#62]
Android Studio can't find `@GsonTypeAdapterFactory` annotation. 
I am using `apt 'com.ryanharter.auto.value:auto-value-gson:0.4.0'`, I also have tried with `apt 'com.ryanharter.autogson:auto-gson:0.1-SNAPSHOT'` from `maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }`.

Not sure if I should use `apt`, `provided` or `compile` for importing.

**Comment by rharter** [comment]
You need to use both `apt` and `provided`.

```groovy
apt 'com.ryanharter.auto.value:auto-value-gson:0.4.0'
provided 'com.ryanharter.auto.value:auto-value-gson:0.4.0'
```

**Comment by rharter** [comment]
I'll add that to the readme.
