### ISSUE TITLE
Upload 0.4.1 to maven

### ISSUE THREAD

**Issue by oguzbabaoglu** [rharter/auto-value-gson#63]
0.4.1 doesn't seem to be on maven. Could you upload it?

http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22auto-value-gson%22
https://bintray.com/bintray/jcenter/com.ryanharter.auto.value%3Aauto-value-gson

Also couldn't see it in snapshots repo 
https://oss.sonatype.org/content/repositories/snapshots/com/ryanharter/auto/value/auto-value-gson/

**Comment by rharter** [comment]
I've fixed this, but you'll need to switch to 0.4.2.  There was a threading issue with the upload.
