### ISSUE TITLE
Generics with parameterized fields

### ISSUE THREAD

**Issue by oguzbabaoglu** [rharter/auto-value-gson#65]
A model with a parameterized field such as this one:

``` java
@AutoValue
public abstract class ListResponse<T> {
  public abstract List<T> results();
}
```

Will produce:

``` java
this.resultsAdapter = gson.getAdapter(new TypeToken<List<T>>(){});
```

This doesn't work since `T` is erased during runtime.

**Comment by skylve** [comment]
Same issue happens when you have this :
```
public abstract class Base<T> {
  public abstract T value();
}

@AutoValue
public abstract class ChildInteger extends Base<Integer> {
}
```

Will produce:
```
private final TypeAdapter<T> valueAdapter;
```

Auto-value generate the correct type when using this pattern (`$AutoValue_ChildInteger` use the concrete type)
