### ISSUE TITLE
Unable to Serialize null field

### ISSUE THREAD

**Issue by dkpalmer** [rharter/auto-value-gson#67]
I have a need to serialize a null field. When I mark the field as `@Nullable`, I see the GsonTypeAdapter `write(JsonWriter, Object)` method wrap the field adapter's `write()` call in a null check. But if I remove `@Nullable`, my builder/factory methods complain about the null value. Is there any way around this?

It looks like [23](https://github.com/rharter/auto-value-gson/pull/23) could be related?

For clarity, I am calling serializeNulls in my GsonBuilder. Perhaps the write method's GsonTypeAdapter could check that flag in the JsonWriter to bypass the above mentioned null check?

**Comment by hzsweers** [comment]
Closed by #78
