### ISSUE TITLE
ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast

### ISSUE THREAD

**Issue by mdudzak** [rharter/auto-value-gson#68]
I made model from example of WebResponse where i'm using Type parameter like so :

```
@AutoValue
public abstract class SocialStream<T> {
  public abstract int id();
  ......
  ......

  public abstract List<T> messages();

  public static <T> TypeAdapter<SocialStream<T>> typeAdapter(Gson gson, TypeToken<? extends SocialStream<T>> typeToken) {
    return new AutoValue_SocialStream.GsonTypeAdapter(gson, typeToken);
  }
}
```

As you can see i also passed typetoken to AutoValue typeAdapter, and everything seems to work, i already logged whole json, but problem occurs when i try to use it as my model.

```
SocialStream<FacebookPost> post = getList().get(0);
```

method getList() returns array of these messages and this is the line where i'm getting exception: 

```
java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to com.example.model.FacebookPost
```

**Comment by alexleekt** [comment]
+1 i'm also experiencing the same problem.

**Comment by oguzbabaoglu** [comment]
See #65

**Comment by aegis123** [comment]
I'm also seeing this. 

I download the sample code which generates and checked the generated code and I see a little discrepancy.

sample code:
```
ParameterizedType type = (ParameterizedType) typeToken.getType();
Type[] typeArgs = type.getActualTypeArguments();
this.listAdapter = (TypeAdapter<List<T>>) gson.getAdapter(TypeToken.getParameterized(List.class, typeArgs[0]));
```

my project:
```
ParameterizedType type = (ParameterizedType) typeToken.getType();
Type[] typeArgs = type.getActualTypeArguments();
this.listAdapter = gson.getAdapter(new TypeToken<List<T>>(){});
```

I'm using auto value 1.3, auto-gson 0.4.4 and gson 2.8.0. or is this feature only available in a newer auto-gson version?

**Comment by HamedMasafi** [comment]
+1 for same problem (using version 1.1.1)

**Comment by hzsweers** [comment]
This is an issue with adapters not being registered to the gson instance correctly. Take a look at the factory generation API. If this is occurring even with a factory and correct wiring, please feel free to comment with a reproducible sample
