### ISSUE TITLE
`AutoValueGson_MyAdapterFactory` not found

### ISSUE THREAD

**Issue by oldergod** [rharter/auto-value-gson#69]
When creating a `@GsonTypeAdapterFactory`, the constructor that should be available to use into the `static create()` is not found.

For instance, see this project https://github.com/satoshun-example/android-architecture with Android Studio 2.2, upgraded to the latest gradle wrapper and gradle plugin.

**Comment by rharter** [comment]
Looks fine to me.  Have you built the project?  When you first write it it will show up as unfound because it doesn't get generated until you build.

![screen shot 2016-09-22 at 8 59 01 am](https://cloud.githubusercontent.com/assets/1296750/18750964/dbc666a0-80a2-11e6-9731-854a48a3b8a7.png)

**Comment by oldergod** [comment]
I had working after building this project, thanks a lot.

However, I cannot have it working on my project. I tried to isolate as much as I could here: https://github.com/sandboxing/testing-auto-value-gson ※ _Sorry, I should have done it the first time_

I get an error and I cannot find out what is missing here
```
app/src/main/java/autovalue/testing/oldering/io/myapplication/AutoValueGsonTypeAdapterFactory.java:9: error: cannot find symbol
        return new AutoValueGson_AutoValueGsonTypeAdapterFactory();
                   ^
  symbol:   class AutoValueGson_AutoValueGsonTypeAdapterFactory
  location: class AutoValueGsonTypeAdapterFactory
1 error
:app:compileDebugJavaWithJavac FAILED
```

**Comment by oldergod** [comment]
Confirmed on a CircleCI build to be sure it was a local problem. https://circleci.com/gh/sandboxing/testing-auto-value-gson/5

**Comment by oldergod** [comment]
@rharter You must have a lot on your plate and I know I screwed up not showing the minimised version of my project at first but I would _really_ appreciate any help finding what is missing in my configuration.

**Comment by oldergod** [comment]
So I got it working but I am not sure I should be satisfied with the step I took.

You can see [here](https://github.com/sandboxing/testing-auto-value-gson/commits/master) the only difference between the failing and fixed build.

Basically, if I, in an other class, created a static `typeAdapter` creator as so

```java
    public static TypeAdapter<Foo> typeAdapter(Gson gson) {
        return new AutoValue_Foo.GsonTypeAdapter(gson);
    }
```

Then, the `@GsonTypeAdapterFactory` would generate the Factory constructor as expected, but I wanted to the use `@GsonTypeAdapterFactory` so I would not have to set the `typeAdapter` for every class.  
Isn't it a bug?

**Comment by rharter** [comment]
Ahh, yes, this is actually how it's designed to work. Unfortunately,
without that static factory method in the class, there's no way for the
type adapter factory to access the generated package private type adapter
reliably (we can't guarantee your factory is in the same package as all of
your models).

We've been talking about a reflection based solution for this, but for now
all of your AutoValue annotated classes need static type adapter methods.

**Comment by oldergod** [comment]
I see better now. Thank you for the follow.
