### ISSUE TITLE
buildUpon() not working

### ISSUE THREAD

**Issue by UnknownUntilNow** [rharter/auto-value-gson#7]
The generated constructor contains a field for a builder:

AutoValue_Message(String text, Message.Builder buildUpon) {
    super(text, buildUpon);
}

(This results in a compile time error)

**Comment by rharter** [comment]
I've filed this with the AutoValue project and it's been taken. https://github.com/google/auto/issues/281

**Comment by rharter** [comment]
Workaround is to simply make your `buildUpon()` method return `new AutoValue_Message.Builder();`.
