### ISSUE TITLE
Problem with Generics and AdapterFactory

### ISSUE THREAD

**Issue by BraisGabin** [rharter/auto-value-gson#79]
If I add the [example with generics](https://github.com/rharter/auto-value-gson#the-typeadapter) to my code:

``` java
@AutoValue
public abstract class Foo<A, B, C> {
    // properties...

    public static <A, B, C> TypeAdapter<Foo<A, B, C>> typeAdapter(Gson gson,
                                                                  TypeToken<? extends Foo<A, B, C>> typeToken) {
        return new AutoValue_Foo.GsonTypeAdapter(gson, typeToken);
    }
}
```

I have this error on my `AdapterFactory`:

> /path/app/build/generated/source/apt/staging/debug/package/AutoValueGson_MyAdapterFactory.java
> Error:(33, 78) error: cannot find symbol class A
> Error:(33, 81) error: cannot find symbol class B
> Error:(33, 84) error: cannot find symbol class C

To fix it I must change `TypeToken<? extends Foo<A, B, C>> typeToken` to `TypeToken<? extends Foo> typeToken`:

``` java
@AutoValue
public abstract class Foo<A, B, C> {
    // properties...

    public static <A, B, C> TypeAdapter<Foo<A, B, C>> typeAdapter(Gson gson,
                                                                  TypeToken<? extends Foo> typeToken) {
        return new AutoValue_Foo.GsonTypeAdapter(gson, typeToken);
    }
}
```

What's the problem? The example? Am I missing anything? Is my "fix" correct?

**Comment by hzsweers** [comment]
Just documenting for clarity after taking a peek, the issue is in the generated factory itself, not in the actual class definition.

```java
public final class AutoValueGson_SampleAdapterFactory extends SampleAdapterFactory {
  @Override
  @SuppressWarnings("unchecked")
  public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
    Class<?> rawType = type.getRawType();
    if (Foo.class.isAssignableFrom(rawType)) {
      return (TypeAdapter<T>) Foo.typeAdapter(gson, (TypeToken<? extends Foo<A, B, C>>) type);
    } else {
      return null;
    }
  }
}

```
