### ISSUE TITLE
Gson 2.4 now supports @SerializedName on methods, description should be updated

### ISSUE THREAD

**Issue by dimsuz** [rharter/auto-value-gson#8]
Since recent release gson-2.4, it supports `@SerializedName` on methods (see [CHANGELOG](https://github.com/google/gson/blob/master/CHANGELOG.md)).

So I guess this part of `README.md` should be updated somehow:

```
Note: Since Gson's built in SerializedName annotation can't be used on methods, you'll have to change your SerializedName import to com.ryanharter.auto.value.gson.SerializedName.
```

I am not sure how exactly you want to handle this - either by dropping your version of `@SerializedName` and removing respective note from README or by leaving this custom annotation for those who use earlier Gson version and just mentioning that since `gson-2.4` it is not needed.

So I didn't send PR :)

**Comment by rharter** [comment]
Resolved this in commit f58ee01985a403ec67005441020028d1b3148c1d.

I chose to simply remove the references, since the code change removing the custom attribute was already in place, and simply bumped the version so that people can still use the old version if they choose.
