### ISSUE TITLE
Fields that use type parameters currently not supported

### ISSUE THREAD

**Issue by cxzhang2** [rharter/auto-value-gson#86]
Couldn't figure out how to word the topic, but the following example should be clear:

```
@AutoValue
public abstract class Parent<T> {
   public abstract Child1<T>();
   public abstract Child2<T>();
   public static <T> TypeAdapter...
}
```

currently generates the following code:

```
public GsonTypeAdapter(Gson gson, TypeToken<? extends Parent<T>> typeToken){
  ParameterizedType type = ...
  Type[] typeArgs = ...
  this.child1Adapter = gson.getAdapter(new TypeToken<Child1<T>>(){});
  ...
}
```

This is an error because TypeToken does not support things such as `new TypeToken<Child<T>>(){}`, and (T) will always captured as an Object and lead to potential CastException's at runtime.  Thoughts?

**Comment by oguzbabaoglu** [comment]
Support for this was added in #66 but not released yet.

**Comment by cxzhang2** [comment]
Thanks!  Sorry I missed this, closing.
