### ISSUE TITLE
Support non JSON properties

### ISSUE THREAD

**Issue by ansman** [rharter/auto-value-gson#90]
I have some properties that aren't sent as JSON and are created dynamic (such as a `creation` timestamp). It would be nice to support dynamic default values and be able to exclude fields from the JSON.

**Comment by hzsweers** [comment]
Some form of this was already added right?

**Comment by jlmcdonnell** [comment]
@hzsweers Do you know how this can be achieved? I can't find a way to prevent auto-value-gson from generating code for non JSON properties.

**Comment by hzsweers** [comment]
We've talked about making a separate set of annotations that can be shared and understood, `@Transient` being one. Ryan is out for a bit and I'm waiting to hear from him on that.

One potential issue though is that you would have to specify some sort of default or handling for required transient fields

**Comment by jffiorillo** [comment]
Is this still on hold ?

**Comment by hzsweers** [comment]
This is sort of two requests in one

1. Ability to ignore some properties
2. Ability to customize dynamic alternative values for ignored properties

#1 is already supported.

For #2, I'd prefer that be solved by #132
