### ISSUE TITLE
Allow null values for primitive types

### ISSUE THREAD

**Issue by fractalemagic** [rharter/auto-value-gson#92]
Gson lets you deserialize null for primitive types, it resolves to the default value ie. 0 or false

Are there any plans to support this?

**Comment by autonomousapps** [comment]
Building on @fractalemagic 's question, is it possible to create a custom GsonTypeAdapter that can turn a `null` into a primitive type? I was hoping that allowing default values would help, but my API is returning 'null' for ints and longs, and I'm getting the error

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
```

**Comment by hzsweers** [comment]
seems kind of silly/wasted space, tell your backend to stop sending keys with null values?

**Comment by autonomousapps** [comment]
@hzsweers I don't live in that ideal world, unfortunately. You should actually see the amount of 'wasted space' I currently have in one of my AutoValue classes to get around the fact that I can't currently deserialize null values into default values.

**Comment by hzsweers** [comment]
Wasted space on the wire I mean. They're sending keys in the payload that exist solely to tell you they don't exist.

In any case, AVG already initializes these fields to these defaults so I'm not sure what else you need?

**Comment by autonomousapps** [comment]
As a matter of fact, I agree with you. I created a ticket for the API guys to send default values, but then the iOS guys complained that they already had specialized logic for what to do in the presence of a null value, and so nothing happened.

To answer your question, yes, I'd like AVG to skip keys if their value is `null`. I believe this PR addresses that: https://github.com/rharter/auto-value-gson/pull/100

As a workaround in my own code, I'm using object-versions of primitives, annotated with `@Nullable`, and then requiring client code to call wrappers that automatically convert null values to default values, with the aim of avoiding null checks downstream.

For example:

```java
@Nullable protected abstract Long id();
public long getId() {
    return nullSafeLong(id());
}
```

Ends up adding a lot of boilerplate :-/

**Comment by jettbow** [comment]
We faced the issue when we migrated from gson to auto-value-gson.
I think this one should be fixed because skipping null is how gson handle it.

**Comment by rharter** [comment]
It pains me to accept this, and I firmly believe it is the wrong behavior for the library to make assumptions in an attempt to fix a broken API (if it's not a nullable value, the API shouldn't send null).  That being said, I am going to accept PR #100 for this since it is Gson's default functionality.
