### ISSUE TITLE
Snapshots of the latest development version are not available

### ISSUE THREAD

**Issue by zsavely** [rharter/auto-value-gson#93]
[This directory ](https://oss.sonatype.org/content/repositories/snapshots/com/ryanharter/auto/value/) `auto-value-gson` was last modified on Thu Apr 07 01:29:01 UTC 2016. The latest snapshot there is version `0.2` but the next version is `0.4.5`.

**Comment by hzsweers** [comment]
@zsavely are you still having this issue?

**Comment by zsavely** [comment]
Yes
